# Generated by Django 3.0.8 on 2020-08-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200830_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='pid',
            new_name='product',
        ),
    ]
